# GENERATED by scripts/gen_topic_constants.py — do not edit.
# Source: shared/contracts/topics.yaml
from __future__ import annotations

CONTRACT_VERSION = "1.0.0"
WS_ENDPOINT = "ws://localhost:9090"
WS_SCHEMA = "websocket_messages"

PER_DRONE_STATE = "drones.{drone_id}.state"
PER_DRONE_TASKS = "drones.{drone_id}.tasks"
PER_DRONE_FINDINGS = "drones.{drone_id}.findings"
PER_DRONE_CAMERA = "drones.{drone_id}.camera"
PER_DRONE_CMD = "drones.{drone_id}.cmd"
SWARM_BROADCAST = "swarm.broadcasts.{drone_id}"
SWARM_VISIBLE_TO = "swarm.{drone_id}.visible_to.{drone_id}"
SWARM_OPERATOR_ALERTS = "swarm.operator_alerts"
EGS_STATE = "egs.state"
EGS_REPLAN_EVENTS = "egs.replan_events"
EGS_OPERATOR_ACTIONS = "egs.operator_actions"
MESH_ADJACENCY = "mesh.adjacency_matrix"

def per_drone_state_channel(drone_id: str) -> str:
    return PER_DRONE_STATE.replace("{drone_id}", drone_id)

def per_drone_tasks_channel(drone_id: str) -> str:
    return PER_DRONE_TASKS.replace("{drone_id}", drone_id)

def per_drone_findings_channel(drone_id: str) -> str:
    return PER_DRONE_FINDINGS.replace("{drone_id}", drone_id)

def per_drone_camera_channel(drone_id: str) -> str:
    return PER_DRONE_CAMERA.replace("{drone_id}", drone_id)

def per_drone_cmd_channel(drone_id: str) -> str:
    return PER_DRONE_CMD.replace("{drone_id}", drone_id)

def swarm_broadcast_channel(drone_id: str) -> str:
    return SWARM_BROADCAST.replace("{drone_id}", drone_id)

def swarm_visible_to_channel(drone_id: str) -> str:
    return SWARM_VISIBLE_TO.replace("{drone_id}", drone_id)

