"""Generate Python and Dart channel constants from shared/contracts/topics.yaml.

Usage:
    python -m scripts.gen_topic_constants            # write files
    python -m scripts.gen_topic_constants --check    # exit 1 if generated files are stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
YAML_PATH = ROOT / "shared" / "contracts" / "topics.yaml"
PY_OUT = ROOT / "shared" / "contracts" / "topics.py"
DART_TOPICS_OUT = ROOT / "frontend" / "flutter_dashboard" / "lib" / "generated" / "topics.dart"
DART_VERSION_OUT = ROOT / "frontend" / "flutter_dashboard" / "lib" / "generated" / "contract_version.dart"
VERSION_PATH = ROOT / "shared" / "VERSION"

PY_HEADER = (
    "# GENERATED by scripts/gen_topic_constants.py — do not edit.\n"
    "# Source: shared/contracts/topics.yaml\n"
    "from __future__ import annotations\n\n"
)

DART_HEADER = (
    "// GENERATED by scripts/gen_topic_constants.py — do not edit.\n"
    "// Source: shared/contracts/topics.yaml\n\n"
)


def _load() -> dict:
    return yaml.safe_load(YAML_PATH.read_text())


def _py_const_name(group: str, key: str) -> str:
    return f"{group.upper()}_{key.upper()}"


def _python(reg: dict, version: str) -> str:
    out = [PY_HEADER]
    out.append(f'CONTRACT_VERSION = "{version}"\n')
    out.append(f'WS_ENDPOINT = "{reg["websocket"]["endpoint"]}"\n')
    out.append(f'WS_SCHEMA = "{reg["websocket"]["schema"]}"\n\n')

    helpers: list = []
    for group_name, entries in reg["redis"].items():
        for key, entry in entries.items():
            const = _py_const_name(group_name, key)
            channel = entry["channel"]
            out.append(f'{const} = "{channel}"\n')
            if "{drone_id}" in channel:
                fn = f"{group_name}_{key}_channel"
                helpers.append(
                    f"def {fn}(drone_id: str) -> str:\n"
                    f'    return {const}.replace("{{drone_id}}", drone_id)\n\n'
                )
    out.append("\n")
    out.extend(helpers)
    return "".join(out)


def _dart(reg: dict, version: str) -> tuple:
    topics = [DART_HEADER, "class Channels {\n"]
    topics.append(f'  static const wsEndpoint = "{reg["websocket"]["endpoint"]}";\n')
    topics.append(f'  static const wsSchema = "{reg["websocket"]["schema"]}";\n\n')
    for group_name, entries in reg["redis"].items():
        for key, entry in entries.items():
            channel = entry["channel"]
            camel = "".join(p.capitalize() for p in f"{group_name}_{key}".split("_"))
            camel = camel[0].lower() + camel[1:]
            if "{drone_id}" in channel:
                # Dart uses ${} interpolation
                dart_template = channel.replace("{drone_id}", "$droneId")
                topics.append(f'  static String {camel}(String droneId) => "{dart_template}";\n')
            else:
                topics.append(f'  static const {camel} = "{channel}";\n')
    topics.append("}\n")

    version_dart = f'{DART_HEADER}const contractVersion = "{version}";\n'
    return "".join(topics), version_dart


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        existing = path.read_text() if path.exists() else ""
        if existing != content:
            print(f"STALE: {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main(argv: list = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    reg = _load()
    version = VERSION_PATH.read_text().strip()

    py = _python(reg, version)
    dart_topics, dart_version = _dart(reg, version)

    ok = True
    ok &= _write_or_check(PY_OUT, py, args.check)
    ok &= _write_or_check(DART_TOPICS_OUT, dart_topics, args.check)
    ok &= _write_or_check(DART_VERSION_OUT, dart_version, args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
